version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/jenkins  # EC2 내부 배포 할 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh    # ApplicationStart 단계에서 해당 파일을 실행해라
      timeout: 60
      runas: ec2-user

#version: 0.0
#os: linux
#files:
#  - source: /
#    destination: /home/ec2-user
#hooks:
#  ApplicationStop:
#    - location: scripts/stop_process.sh
#  BeforeInstall:
#    - location: scripts/remove.sh # 이전 생성된 파일 제거
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#  ApplicationStart:
#    - location: scripts/start_process.sh 
